version: "2.2"
services:
  my-postgres:
    image: postgres
    ports:
      - "9000:5432"
    environment:
      # this setup will also represent in ./config/config.json
      POSTGRES_USER: emilia
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kumparan
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql